# Python versions, numpy pins, zip_keys, and compiler versions
# are inherited from conda-forge's global pinning:
# https://github.com/conda-forge/conda-forge-pinning-feedstock
#
# Only add overrides here if you need to diverge from conda-forge defaults.
